package com.example.movieapp;
import androidx.appcompat.app.AppCompatActivity;

import java.util.ArrayList;

public class MovieData extends AppCompatActivity {
    private static String[][] dataMovies = new String[][]{

            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/zixTWuMZ1D8EopgOhLVZ6Js2ux3.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/8Bgdfv1oN9Mw0YuMHP6fw8KzDkc.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/aBmNiCOmZbtdR1rr3SFQSMvnqCI.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/mQsO4JrmYWKTXtFg7u3zhYGiXfM.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/o94R8Z59lrwbZ0LcUkDSPu1GS7q.jpg",
                    "Joker",
                    "October 2, 2019",
                    "84%",
                    "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
                    "Todd Philips",
                    "Joaquin Phoenix",
                    "Arthur Fleck/ Joker",
                    "Robert De Niro",
                    "Muray Franklin",
                    "Zazie Beetz",
                    "Sophie Dumond",
                    "Frances Conroy",
                    "Penny Fleck",
                    "Bret Cullen",
                    "Thomas Wayne",
                    "2h 2m",
                    "Crime, Thriller, Drama",
                    "$55,000,000.00",
                    "$936,887,108.00"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/vqzNJRH4YyquRiWxCCOH0aXggHI.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/9N7FNKUhjtinrNPy8ANvXrB7iEr.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/ekQbEIKh26jbz17P0wwLbo6uNs9.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/zRQSWGCmVkYC7s0WxSJla5R4dPX.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/gXCHO4NtCd7cnAiVXbz4drekgq5.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/dUAFC9E1oVTDKFXCYcetPuOMXYA.jpg",
                    "Terminator: Dark Fate",
                    "October 23, 2019",
                    "64%",
                    "More than two decades have passed since Sarah Connor prevented Judgment Day, changed the future, and re-wrote the fate of the human race. Dani Ramos is living a simple life in Mexico City with her brother and father when a highly advanced and deadly new Terminator – a Rev-9 – travels back through time to hunt and kill her. Dani's survival depends on her joining forces with two warriors: Grace, an enhanced super-soldier from the future, and a battle-hardened Sarah Connor. As the Rev-9 ruthlessly destroys everything and everyone in its path on the hunt for Dani, the three are led to a T-800 from Sarah’s past that may be their last best hope",
                    "Tim Mille",
                    "Natalia Reye",
                    "Daniela 'Dani' Ramo",
                    "Mackenzie Davi",
                    "Grac",
                    "Linda Hamilto",
                    "Sarah Conno",
                    "Gabriel Lun",
                    "Rev-",
                    "Arnold Schwarzenegge",
                    "Carl / The Terminato",
                    "2h 8",
                    "Action, Science Fictio",
                    "$185,000,000.0",
                    "$125,650,308.0"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/vqzNJRH4YyquRiWxCCOH0aXggHI.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/9N7FNKUhjtinrNPy8ANvXrB7iEr.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/ekQbEIKh26jbz17P0wwLbo6uNs9.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/zRQSWGCmVkYC7s0WxSJla5R4dPX.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/gXCHO4NtCd7cnAiVXbz4drekgq5.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/dUAFC9E1oVTDKFXCYcetPuOMXYA.jpg",
                    "Cars",
                    "June 8, 2006",
                    "67%",
                    "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
                    "John Lasseter",
                    "Owen Wilson",
                    "Lightning McQueen",
                    "Paul Newman",
                    "Doc Hudson",
                    "Bonnie Hunt",
                    "Sally Carrera",
                    "Larry the Cable Guy",
                    "Mater",
                    "Tony Shalhoub",
                    "Luigi",
                    "1h 57m",
                    "Action, Adventure, Comedy, Family",
                    "$120,000,000.00",
                    "$461,983,149.00"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/36o5mpbQVdxOf9kUxWw7SllOuk.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/9MgDCYBBVBl4lM1DuxNIIbCHlKy.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/oqMPIsXrl9SZkRfIKN08eFROmH6.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/kq5DDnqqofoRI0t6ddtRlsJnNPT.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/eoBvK34M52no6voo9Qibrd1S0nX.jpg",
                    "The Lion King",
                    "Juny 12, 2019",
                    "71%",
                    "Simba idolises his father, King Mufasa, and takes to heart his own royal destiny. But not everyone in the kingdom celebrates the new cub's arrival. Scar, Mufasa's brother—and former heir to the throne—has plans of his own. The battle for Pride Rock is ravaged with betrayal, tragedy and drama, ultimately resulting in Simba's exile. With help from a curious pair of newfound friends, Simba will have to figure out how to grow up and take back what is rightfully his.",
                    "Jon Favreau",
                    "Donald Glover",
                    "Simba",
                    "Beyoncé Knowles",
                    "Nala",
                    "James Earl Jones",
                    "Mufasa",
                    "Chiwetel Ejiofor",
                    "Scar",
                    "Alfre Woodard",
                    "Sarabi",
                    "1h 58m",
                    "Animation, Adventure, Drama",
                    "$260,000,000.00",
                    "$1,649,676,757.00"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/tBuabjEqxzoUBHfbyNbd8ulgy5j.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/gD8jlGkQC8GBajulNlIzBK1YEO1.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/e8CUyxQSE99y5IOfzSLtHC0B0Ch.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/oGUmQBU87QXAsnaGleYaAjAXSlj.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/asiOPYCbcQYYG5SbxhBYH8xOIys.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/4PfVxrZ4pXXZjTvMzf9UfGpV53K.jpg",
                    "Maleficent: Mistress of Evil",
                    "October 16, 2019",
                    "72%",
                    "Maleficent and her goddaughter Aurora begin to question the complex family ties that bind them as they are pulled in different directions by impending nuptials, unexpected allies, and dark new forces at play.",
                    "Joachim Rønning",
                    "Angelina Jolie",
                    "Maleficent",
                    "Elle Fanning",
                    "Princess Aurora",
                    "Michelle Pfeiffer",
                    "Queen Ingrith",
                    "Harris Dickinson",
                    "Prince Philip",
                    "Sam Riley",
                    "Diaval",
                    "1h 58m",
                    "Fantasy, Adventure, Family",
                    "$85,000,000.00",
                    "$385,990,275.00"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/kvpNZAQow5es1tSY6XW2jAZuPPG.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/kuqFzlYMc2IrsOyPznMd1FroeGq.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/PhWiWgasncGWD9LdbsGcmxkV4r.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/be1bVF7qGX91a6c5WeRPs5pKXln.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/aB0o6r5msso6tCXTuVgKVO4wRqg.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/2EpyDXqw1oyJnKayu2XshczjiBN.jpg",
                    "Fast and Furious Presents: Hobbs and Shaw",
                    "August 1, 2019",
                    "65%",
                    "Ever since US Diplomatic Security Service Agent Hobbs and lawless outcast Shaw first faced off, they just have swapped smacks and bad words. But when cyber-genetically enhanced anarchist Brixton's ruthless actions threaten the future of humanity, both join forces to defeat him. (A spin-off of “The Fate of the Furious,” focusing on Johnson's Luke Hobbs and Statham's Deckard Shaw.)",
                    "David Leitch",
                    "Dwayne Johnson",
                    "Luke Hobbs",
                    "Jason Statham",
                    "Deckard Shaw",
                    "Idris Elba",
                    "Brixton",
                    "Vanessa Kirby",
                    "Hattie Shaw",
                    "Eiza González",
                    "Madame M",
                    "2h 17m",
                    "Action, Adventure, Comedy",
                    "$200,000,000.00",
                    "$760,098,996.00"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/hoIE7Ua7wTVZ0dfdATdf6uLbnnl.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/j8bwiPbTwU7nMqLzXwieGobfL2D.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/d140yTWCle6rYUGE9GIVZVPaPng.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/xlCX9uilyLOu6zKrBNsdafzNYG1.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/w2RrVNLQa4ApXhpIgWTkpNVS2kd.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/wEy5qSDT5jT3ZASc2hbwi59voPL.jpg",
                    "Charlie's Angels",
                    "November 14, 2019",
                    "76%",
                    "When a systems engineer blows the whistle on a dangerous technology, Charlie's Angels from across the globe are called into action, putting their lives on the line to protect society.",
                    "Elizabeth Banks",
                    "Kristen Stewart",
                    "Sabina Wilson",
                    "Naomi Scott",
                    "Elena Houghlin",
                    "Ella Balinska",
                    "Jane Kano",
                    "Elizabeth Banks",
                    "Bosley",
                    "Patrick Stewart",
                    "Bosley",
                    "1h 58m",
                    "Action, Adventure, Comedy",
                    "$-",
                    "$-"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/lcq8dVxeeOqHvvgcte707K0KVx5.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/ip7aXVH8s6wXv8cY6KI14OZgCI8.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/92sBuFC8tWPG7IqGDJNxysT7tIF.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/r3A7ev7QkjOGocVn3kQrJ0eOouk.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/rOVBKURoR7TrG8MYxTuNUFj3E68.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/qjYcO8jKNlb7lnJ05vh2U7lNt8r.jpg",
                    "Spider-Man: Far from Home",
                    "June 28, 2019",
                    "76%",
                    "Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.",
                    "Jon Watts",
                    "Tom Holland",
                    "Peter Parker/Spider-man",
                    "Jake Gyllenhaal",
                    "Quentin Beck / Mysterio",
                    "Zendaya",
                    "Michelle 'MJ' Jones",
                    "Jon Favreau",
                    "Harold 'Happy' Hogan",
                    "Samuel L. Jackson",
                    "Nick Fury",
                    "2h 9m",
                    "Action, Adventure, Science Fiction",
                    "$160,000,000.00",
                    "$1,131,450,163.00"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/3iYQTLGoy7QnjcUYRJy4YrAgGvp.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/yeaEd4P4kNlRkDqzunsQeh24rQm.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/d140yTWCle6rYUGE9GIVZVPaPng.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/7XEzMCdMQffq8PrkLYjYb7QpIgW.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/k0qx65csI86rAFBR4Sal7phY3Vl.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/cPsYncbHK7J76Sm4bc1rtgRh5qf.jpg",
                    "Aladin",
                    "May 22, 2019",
                    "71%",
                    "A kindhearted street urchin named Aladdin embarks on a magical adventure after finding a lamp that releases a wisecracking genie while a power-hungry Grand Vizier vies for the same lamp that has the power to make their deepest wishes come true.",
                    "Guy Ritchie",
                    "Mena Massoud",
                    "Aladin",
                    "Naomi Scott",
                    "Jasmine",
                    "Will Smith",
                    "Genie",
                    "Marwan Kenzari",
                    "Jafar",
                    "Navid Negahban",
                    "The Sultan",
                    "2h 8m",
                    "Adventure, Fantasy, Romance, Comedy, Family",
                    "$183,000,000.00",
                    "$1,047,612,394.00"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/1YjdSym1jTG7xjHSI0yGGWEsw5i.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/lrhth7yK9p3vy6p7AabDUM1THKl.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/8CgFKCZJVwZxa1F88n8drEux0vT.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/z3dvKqMNDQWk3QLxzumloQVR0pv.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/opEemSnjnN4hbwymHz5P0VVuk4F.jpg",
                    "Avengers: Infinity War",
                    "April 25, 2018",
                    "83%",
                    "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
                    "Joe Russo",
                    "Robert Downey Jr.",
                    "Tony Stark / Iron Man",
                    "Chris Hemsworth",
                    "Thor Odinson",
                    "Chris Evans",
                    "Steve Rogers / Captain America",
                    "Mark Ruffalo",
                    "Bruce Banner / The Hulk",
                    "Scarlett Johansson",
                    "Natasha Romanoff / Black Widow",
                    "2h 29m",
                    "Action, Adventure, Science Fiction",
                    "$300,000,000.00",
                    "$2,046,239,637.00"
            },
    };

    private static String[][] dataTvShow = new String[][]{
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/qJdfO3ahgAMf2rcmhoqngjBBZW1.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/fG4XAevTHgb5nQXUyytU78FAZSD.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/dLdXHfbJ7TMe3qbtNzPpSLuaMos.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/xLZHw2muESIS7zuWFM5yci6rXer.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/ycwiu89cpjqCtSNC5FjbJggjj5R.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/uU2VLWHkKZN0UkYVJBf1s1z2l3k.jpg",
                    "Rick and Morty",
                    "December 2, 2013",
                    "86%",
                    "Rick is a mentally-unbalanced but scientifically-gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
                    "Dan Harmon",
                    "Justin Roiland",
                    "Rick Sanchez / Morty Smith",
                    "Chris Parnell",
                    "Jerry Smith",
                    "Spencer Grammer",
                    "Summer Smith",
                    "Sarah Chalke",
                    "Beth Smith",
                    "Tom Kenny",
                    "Bad Cop / Mr. Jellybean",
                    "22m",
                    "Science Fiction, Fantasy, Action, Adventure, Animation, Comedy"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/gKG5QGz5Ngf8fgWpBsWtlg5L2SF.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/kTe4RYfqFze7N6HX1HEnNfHBZ2w.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/bZWO7WfBYI8iojTFozzqN2X3RWL.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/lRhzzdmt29n8PDi63QX5MLPAUFz.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/zkx3Xwy7w4hFpBNnvfFsKOBQP9V.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/wSn01hjcRFnamCrvhbUJyeMIbxo.jpg",
                    "Arrow",
                    "October 10, 2012",
                    "58%",
                    "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.",
                    "Greg Berlanti",
                    "Stephen Amell",
                    "Oliver Queen",
                    "David Ramsey",
                    "John Diggle",
                    "Katie Cassidy",
                    "Laurel Lance, Black Siren",
                    "Emily Bett Rickards",
                    "Felicity Smoak",
                    "Willa Holland",
                    "Thea Queen / Speedy, Thea Queen",
                    "42m",
                    "Crime, Drama, Action, Adventure, Mystery"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/wHa6KOJAoNTFLFtp7wguUJKSnju.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/kshIWLAwqVXi3Ex2hSD3OUWOpBv.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/d975YyzFgzJbdRL2vdsXZQi8g73.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/3RJQ9sZwmLUI9whOV0eydmbIPoQ.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/mZJBKATPpwnzmqODJKj61YfnVF6.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/jiHus5vnTJF7XCWtWBvfXNl77aK.jpg",
                    "The Flash",
                    "October 7, 2014",
                    "67%",
                    "After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only 'meta-human' who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won't be long before the world learns what Barry Allen has become...The Flash.",
                    "Geoff Johns",
                    "Grant Gustin",
                    "Barry Allen / The Flash",
                    "Candice Patton",
                    "Iris West",
                    "Carlos Valdes",
                    "Reverb, Cisco Ramon",
                    "Danielle Panabaker",
                    "Killer Frost, Caitlin Snow",
                    "Jesse L. Martin",
                    "Joe West",
                    "44m",
                    "Science Fiction, Fantasy, Drama"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/lZMb3R3e5vqukPbeDMeyYGf2ZNG.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/jOGFt9WUezPQFN0xxgTekA2Fyta.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/mhoqQ47tvGlmJQsu2udOsXhKBFk.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/eaJky5Q6X51u0bnQkXyOrM8RnlG.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/sXcn4QnEzvPFV9OiKLvPRyVr7RN.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/kOgVo3qDJ9jXgIZJRJI3I1bm6sA.jpg",
                    "Fear the Walking Dead",
                    "August 23, 2015",
                    "63%",
                    "What did the world look like as it was transforming into the horrifying apocalypse depicted in 'The Walking Dead'? This spin-off set in Los Angeles, following new characters as they face the beginning of the end of the world, will answer that question.",
                    "Robert Kirkman",
                    "Alycia Debnam-Carey",
                    "Alicia Clark",
                    "Colman Domingo",
                    "Victor Strand",
                    "Kim Dickens",
                    "Madison Clark",
                    "Frank Dillane",
                    "Nick Clark",
                    "Rubén Blades",
                    "Daniel Salazar",
                    "43m",
                    "Drama, Horror"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/53P8oHo9cfOsgb1cLxBi4pFY0ja.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/5wou22G4dMRcnpMrRyPfLclZ2lD.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/4QBRarzz68vQCiXteI1TMopj3zn.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/ybmnPYUzcr3RMdaXnZIw2jEw9ju.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/bUzVvgD066zYGJ9amJzgoGivlqD.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/xlAqt3pkr4GU4yNmXzneQd83Qq.jpg",
                    "The Good Doctor",
                    "September 25, 2017",
                    "77%",
                    "A young surgeon with Savant syndrome is recruited into the surgical unit of a prestigious hospital. The question will arise: can a person who doesn't have the ability to relate to people actually save their lives?",
                    "David Shore",
                    "Freddie Highmore",
                    "Shaun Murphy",
                    "Nicholas Gonzalez",
                    "Neil Melendez",
                    "Antonia Thomas",
                    "Claire Browne",
                    "Hill Harper",
                    "Marcus Andrews",
                    "Richard Schiff",
                    "Aaron Glassman",
                    "42m",
                    "Drama"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/jnsvc7gCKocXnrTXF6p03cICTWb.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/iX5HdQdWRPLf5Fx87QDNCdehmI9.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/uh40a9Fv2PJ4nZHEZwsI5g0KiNj.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/iddDcaysDQ6IVMUjJ97Bv3lTBCu.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/83Ynxlv3jV4ahkOiAEfunM7Rez2.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/eHNUaEyNBVuCSxJjPQIgH0keYru.jpg",
                    "Grey's Anatomy",
                    "March 27, 2005",
                    "64%",
                    "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
                    "Shonda Rhimes",
                    "Ellen Pompeo",
                    "Meredith Grey",
                    "Justin Chambers",
                    "Alex Karev",
                    "James Pickens Jr.",
                    "Richard Webber",
                    "Chandra Wilson",
                    "Miranda Bailey",
                    "Patrick Dempsey",
                    "Derek Shepherd",
                    "43m",
                    "Drama"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/g3JsScc7mQCfc3e5e5rXwu7xVVP.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/tTONqzQuAnuMlfM5E0nU9RWukOE.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/wKC9LgqgJRCXuzs1kUKaK7Uicv.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/aCAjUOrV2WG3OaLUvQHVkyk8S2P.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/hUgQJYayUWt3zON9COn0f7RVJxF.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/jx39oEHjGJ2oExhgC7beq0VoCei.jpg",
                    "See",
                    "November 1, 2019",
                    "73%",
                    "A virus has decimated humankind. Those who survived emerged blind. Centuries later when twins are born with the mythic ability to see, their father must protect his tribe against a threatened queen.",
                    "Steven Knight",
                    "Jason Momoa",
                    "Baba Voss",
                    "Alfre Woodard",
                    "Paris",
                    "Sylvia Hoeks",
                    "Queen Kane",
                    "Hera Hilmar",
                    "Maghra",
                    "Archie Madekwe",
                    "Kofun",
                    "60m",
                    "Science Fiction, Drama"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/jnaimWkIVSD9IInmZPyLYarSvvc.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/cUT4hXkqotz0yaSlNxkrlapXVFk.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/bgeqmHfkeFYMXaqr6ReSfN1TWOG.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/jJ1hzF92AclGURRrA1GKs97fg2j.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/zeZmtK4EKK9R2r6bp2nTxMs3ByS.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/opaEeDwL8wgwuwJrC0KpQe5obG5.jpg",
                    "Batwoman",
                    "October 6, 2019",
                    "60%",
                    "Kate Kane, armed with a passion for social justice and a flair for speaking her mind, soars onto the streets of Gotham as Batwoman, an out lesbian and highly trained street fighter primed to snuff out the failing city's criminal resurgence. But don't call her a hero yet. In a city desperate for a savior, Kate must overcome her own demons before embracing the call to be Gotham's symbol of hope",
                    "Greg Berlanti",
                    "Ruby Rose",
                    "Kate Kane",
                    "Rachel Skarsten",
                    "Alice",
                    "Meagan Tandy",
                    "Sophie Moore",
                    "Dougray Scott",
                    "Jacob Kane",
                    "Camrus Johnson",
                    "Luke Fox",
                    "42m",
                    "Science Fiction, Fantasy, Action, Adventure, Mystery, Crime"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/bgbQCW4fE9b6wSOSC6Fb4FfVzsW.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/nWBFY3VSp8EoDBCGhthYqSOYFeA.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/ovCrQfn5Nu5GWatWbUJwMhiSMSG.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/uwpRytLjzz1IvjNanYNlplPVal9.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/nOiJDYiEysyZJHQNPCOSVWw9XzT.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/modltW1yoA2zD6YMOjtmzqC3itR.jpg",
                    "The Blacklist",
                    "September 23, 2013",
                    "70%",
                    "Raymond 'Red' Reddington, one of the FBI's most wanted fugitives, surrenders in person at FBI Headquarters in Washington, D.C. He claims that he and the FBI have the same interests: bringing down dangerous criminals and terrorists. In the last two decades, he's made a list of criminals and terrorists that matter the most but the FBI cannot find because it does not know they exist. Reddington calls this 'The Blacklist'. Reddington will co-operate, but insists that he will speak only to Elizabeth Keen, a rookie FBI profiler.",
                    "Jon Bokenkamp",
                    "James Spader",
                    "Raymond 'Red' Reddington",
                    "Megan Boone",
                    "Elizabeth 'Liz' Keen",
                    "Harry Lennix",
                    "Harold Cooper",
                    "Diego Klattenhoff",
                    "Donald Ressler",
                    "Ryan Eggold",
                    "Tom Keen",
                    "43m",
                    "Drama, Crime, Mystery"
            },
            {"https://image.tmdb.org/t/p/w600_and_h900_bestv2/A3SymGlOHefSKbz1bCOz56moupS.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/gneiMN0OldoxNfmu6dkcBEy0u2k.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/lpjuPm6gjoUCbdqxD0lBAWQAfvv.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/p2JIlYNwjC5ASfmVXvy30DVzXyG.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/lduLl7P0ZRrjMAbwI6WbDbNYVOK.jpg",
                    "https://image.tmdb.org/t/p/w600_and_h900_bestv2/GWpFEYzCCHkWYwiXttkEuPrNW0.jpg",
                    "Brooklyn Nine-Nine",
                    "September 17, 2013",
                    "77%",
                    "A single-camera ensemble comedy following the lives of an eclectic group of detectives in a New York precinct, including one slacker who is forced to shape up when he gets a new boss.",
                    "Daniel J.Goor",
                    "Andy Samberg",
                    "Jake Peralta",
                    "Andre Braugher",
                    "Ray Holt",
                    "Terry Crews",
                    "Terry Jeffords",
                    "Melissa Fumero",
                    "Amy Santiago",
                    "Stephanie Beatriz",
                    "Rosa Diaz",
                    "21m",
                    "Crime, Comedy"
            },
    };

    public static ArrayList<MovieModel> getListDataMovie(){
        ArrayList<MovieModel> listMovies = new ArrayList<>();
        for(String[] aData: dataMovies){
            MovieModel movie= new MovieModel();
            movie.setPoster(aData[0]);
            movie.setPhotoActor1(aData[1]);
            movie.setPhotoActor2(aData[2]);
            movie.setPhotoActor3(aData[3]);
            movie.setPhotoActor4(aData[4]);
            movie.setPhotoActor5(aData[5]);
            movie.setTitle(aData[6]);
            movie.setReleaseDate(aData[7]);
            movie.setUserScore(aData[8]);
            movie.setOverview(aData[9]);
            movie.setDirector(aData[10]);
            movie.setActor1(aData[11]);
            movie.setActorAs1(aData[12]);
            movie.setActor2(aData[13]);
            movie.setActorAs2(aData[14]);
            movie.setActor3(aData[15]);
            movie.setActorAs3(aData[16]);
            movie.setActor4(aData[17]);
            movie.setActorAs4(aData[18]);
            movie.setActor5(aData[19]);
            movie.setActorAs5(aData[20]);
            movie.setRuntime(aData[21]);
            movie.setGenre(aData[22]);
            movie.setBudget(aData[23]);
            movie.setRevenue(aData[24]);

            listMovies.add(movie);
        }
        return listMovies;
    }
    public static ArrayList<MovieModel> getListDataTvShow(){
        ArrayList<MovieModel> listTvShow = new ArrayList<>();
        for (String[] aData: dataTvShow){
            MovieModel tvShow = new MovieModel();
            tvShow.setPoster(aData[0]);
            tvShow.setPhotoActor1(aData[1]);
            tvShow.setPhotoActor2(aData[2]);
            tvShow.setPhotoActor3(aData[3]);
            tvShow.setPhotoActor4(aData[4]);
            tvShow.setPhotoActor5(aData[5]);
            tvShow.setTitle(aData[6]);
            tvShow.setReleaseDate(aData[7]);
            tvShow.setUserScore(aData[8]);
            tvShow.setOverview(aData[9]);
            tvShow.setDirector(aData[10]);
            tvShow.setActor1(aData[11]);
            tvShow.setActorAs1(aData[12]);
            tvShow.setActor2(aData[13]);
            tvShow.setActorAs2(aData[14]);
            tvShow.setActor3(aData[15]);
            tvShow.setActorAs3(aData[16]);
            tvShow.setActor4(aData[17]);
            tvShow.setActorAs4(aData[18]);
            tvShow.setActor5(aData[19]);
            tvShow.setActorAs5(aData[20]);
            tvShow.setRuntime(aData[21]);
            tvShow.setGenre(aData[22]);
            listTvShow.add(tvShow);
        }
        return listTvShow;
    }
}
